# Generated by Django 5.1.7 on 2025-03-08 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0002_alter_coment_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coment',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Posts.author'),
        ),
    ]
